src/SourPickleCMS.Core.Admin/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SourPickleCMS.Core.Attributes;
using SourPickleCMS.Core.Services.DataAccess;
using SourPickleCMS.Core.Models;
using System.ComponentModel;
using SourPickleCMS.Core.Models.ViewModels;
using SourPickleCMS.Core.Helpers;
using SourPickleCMS.Core.Controllers;
using System.IO;
using ImageResizer;
using System.Collections.ObjectModel;

namespace SourPickleCMS.Core.Admin.Controllers
{
    public class PostsController : SourPickleController
    {
        [RoleAuthorize(Roles = AuthRoles.Moderator)]
        public ActionResult Index([DefaultValue("")]string ContentType)
        {
            if (String.IsNullOrWhiteSpace(ContentType)) ContentType = "post";
            IList<Post> model = unitOfWork.PostRepository.GetAllByContentTypeSlug(ContentType).OrderByDescending(o => o.CreateDate).ToList();
            ViewBag.ContentType = unitOfWork.ContentTypeRepository.GetBySlug(ContentType);

            return View(model);
        }

        #region Posts

        [RoleAuthorize(Roles = AuthRoles.Writer)]
        public ActionResult Edit([DefaultValue("")]string id)
        {
            PostEditViewModel model = new PostEditViewModel();

            try
            {
                model.Post = unitOfWork.PostRepository.GetByID(id);
            }
            catch
            {
                model.Post = null;
            }
            if (model.Post == null) return RedirectToAction("Index");
            model.SaveBackup = false;
            model.Revisions = unitOfWork.PostRepository.GetPostRevisionsByParentID(model.Post.Id).OrderByDescending(o => o.CreateDate).ToList();

            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        [RoleAuthorize(Roles = AuthRoles.Writer)]
        public ActionResult Edit(PostEditViewModel model)
        {
            bool saveData = true;

            if (unitOfWork.Session.CurrentUser.Role < 8 && unitOfWork.Session.CurrentUser.Username != model.Post.Username)
            {
                TempData["error"] = "You do not have permission to edit this post.  Please try again.";
                return View("Error");
            }
            if (model.Post == null)
            {
                TempData["error"] = "Page data was unavailable.  Please try again.";
                saveData = false;
            }
            if (String.IsNullOrEmpty(model.Post.Title))
            {
                TempData["error"] = "No page title provided.  Please try again.";
                saveData = false;
            }
            if (String.IsNullOrEmpty(model.Post.Slug))
            {
                TempData["error"] = "No page slug provided.  Please try again.";
                saveData = false;
            }
            if (saveData)
            {
                Post tosave = unitOfWork.PostRepository.GetByID(model.Post.Id);

                tosave.LastUpdatedDate = DateTime.Now;
                if (model.Post.Category != null) tosave.Category = unitOfWork.CategoryRepository.GetBySlug(model.Post.Category.Slug, model.Post.ContentType.Slug);
                tosave.Body = model.Post.Body;
                tosave.Title = model.Post.Title;
                tosave.TemplateName = model.Post.TemplateName;
                tosave.Status = model.Post.Status;
                tosave.Order = model.Post.Order;
                tosave.Role = model.Post.Role;
                tosave.Slug = model.Post.Slug;
                tosave.TemplateName = model.Post.TemplateName;
                if (tosave.Fields != null)
                {
                    foreach (Field field in tosave.Fields.Where(f => f.IsCustomField == true))
                    {
                        model.Post.Fields.Add(field);
                    }
                }
                model.Post = tosave;
                try
                {
                    if (model.SaveBackup)
                    {
                        Post backup = model.Post.GetBackupCopy();
                        backup.Status = "revision";
                        backup.CreateDate = DateTime.Now;
                        backup.ParentID = model.Post.Id;
                        unitOfWork.PostRepository.Save(backup);
                    }

                    unitOfWork.PostRepository.Save(model.Post);
                    TempData["msg"] = "Your " + model.Post.ContentType.Slug + " was saved successfully!";
                }
                catch
                {
                    TempData["error"] = "Error saving page.  Check your input and try again.";
                }
            }

            model.Revisions = unitOfWork.PostRepository.GetPostRevisionsByParentID(model.Post.Id).OrderByDescending(o => o.CreateDate).ToList();
            return View(model);
        }

        [RoleAuthorize(Roles = AuthRoles.Writer)]
        public ActionResult New([DefaultValue("")]string ContentType)
        {
            if (String.IsNullOrWhiteSpace(ContentType)) ContentType = "blog";
            PostEditViewModel model = new PostEditViewModel
            {
                Post = new Post
                {
                    Id = "",
                    ContentType = null,
                    Status = "published"
                },
                Revisions = new List<Post>(),
            };
            model.Post.ContentType = unitOfWork.ContentTypeRepository.GetBySlug(ContentType);
            if (ContentType != "page") model.Post.Category = unitOfWork.CategoryRepository.GetBySlug("uncategorized", ContentType);

            if (model.Post.ContentType.Fields != null && model.Post.ContentType.Fields.Count() > 0)
            {
                model.Post.Fields = model.Post.ContentType.Fields;
            }

            return View("Edit", model);
        }

        [HttpPost]
        [ValidateInput(false)]
        [RoleAuthorize(Roles = AuthRoles.Writer)]
        public ActionResult New(PostEditViewModel model)
        {
            bool saveData = true;

            if (model.Post.Title == null || model.Post.Title == "")
            {
                ModelState.AddModelError("", "No page title provided.  Please try again.");
                saveData = false;
            }
            if (model.Post.Slug == null || model.Post.Slug == "")
            {
                ModelState.AddModelError("", "No page slug provided.  Please try again.");
                saveData = false;
            }

            if (saveData)
            {
                model.Post.Id = "";
                model.Post.CreateDate = DateTime.Now;
                model.Post.LastUpdatedDate = DateTime.Now;
                model.Post.Username = unitOfWork.Session.CurrentUser.Username;
                model.Post.ContentType = unitOfWork.ContentTypeRepository.GetBySlug(model.Post.ContentType.Slug);
                model.Post.Category = unitOfWork.CategoryRepository.GetBySlug("uncategorized", model.Post.ContentType.Slug);

                try
                {
                    model.Post = unitOfWork.PostRepository.Save(model.Post);

                    TempData["msg"] = model.Post.ContentType.Slug + " was saved successfully!";
                    return RedirectToAction("Index", new { ContentType = model.Post.ContentType.Slug });
                }
                catch
                {
                    ModelState.AddModelError("", "Error saving.  Check your input and try again.");
                }
            }

            model.Post.ContentType = unitOfWork.ContentTypeRepository.GetBySlug(model.Post.ContentType.Slug);
            model.Post.Category = unitOfWork.CategoryRepository.GetBySlug("uncategorized", model.Post.ContentType.Slug);

            return View("Edit", model);
        }

        [RoleAuthorize(Roles = AuthRoles.Writer)]
        public ActionResult DeletePost([DefaultValue("")]string ContentType, [DefaultValue("")]string id)
        {
            Post model = unitOfWork.PostRepository.GetByID(id);

            if (model.Username != unitOfWork.Session.CurrentUser.Username)
            {
                TempData["error"] = "You do not have permission to delete this post.";
            }
            else
            {
                if (model != null)
                {
                    if (!String.IsNullOrWhiteSpace(model.AttachedImageId))
                    {
                        Post img = unitOfWork.PostRepository.GetByID(model.AttachedImageId);
                        img.ParentID = null;
                        unitOfWork.PostRepository.Update(img);
                    }

                    unitOfWork.PostRepository.Delete(model);
                    unitOfWork.Save();
                    TempData["msg"] = "Item deleted successfully!";
                }
                else
                {
                    TempData["error"] = "Could not find the specified post.";
                }
            }
            if (ContentType == "ContentTypes-4")
            {
                return RedirectToAction("Media");
            }
            else
            {
                return RedirectToAction("Index", new { ContentType = ContentType });
            }
        }

        #endregion

        #region Categories

        [RoleAuthorize(Roles = AuthRoles.Moderator)]
        public ActionResult Categories([DefaultValue("")]string ContentType)
        {
            IList<Category> model = unitOfWork.CategoryRepository.GetByContentType(ContentType).OrderByDescending(o => o.Name).ToList();
            ViewBag.ContentType = unitOfWork.ContentTypeRepository.GetBySlug(ContentType);

            for (int x = 0; x < model.Count(); x++)
            {
                string id = model[x].Id;
                model[x].PostCount = unitOfWork.PostRepository.GetPostCountByCategory(model[x].Slug, ContentType);
            }
            return View(model);
        }

        [HttpPost]
        [RoleAuthorize(Roles = AuthRoles.Moderator)]

src/SourPickleCMS.Core.Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SourPickleCMS.Core.Services.DataAccess;
using SourPickleCMS.Core.Models;
using SourPickleCMS.Core.Attributes;
using System.ComponentModel;
using SourPickleCMS.Core.Controllers;

namespace SourPickleCMS.Core.Admin.Controllers
{
    [RoleAuthorize(Roles = AuthRoles.Admin)]
    public class UsersController : SourPickleController
    {
        public ActionResult Index()
        {
            IEnumerable<Account> model = unitOfWork.AccountRepository.Get();

            return View(model);
        }

        public ActionResult Edit([DefaultValue("")]string id)
        {
            Account model = new Account();

            try
            {
                model = unitOfWork.AccountRepository.GetByID(id);
            }
            catch
            {
                model = null;
            }
            if (model == null) return RedirectToAction("Index");
            model.Password = "";

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Account model)
        {
            Account account = unitOfWork.AccountRepository.GetByID(model.Id);

            account.Email = model.Email;
            account.Name = model.Name;
            account.Username = model.Username;
            account.LockedReason = model.LockedReason;
            account.IsLocked = model.IsLocked;
            account.IsSuspended = model.IsSuspended;
            account.Role = model.Role;
            account.EmailVerified = model.EmailVerified;

            if (!String.IsNullOrEmpty(model.Password))
            {
                model.Password = SecurityHelper.GetHashedString(model.Password + "$" + account.PasswordSalt);
            }

            unitOfWork.AccountRepository.Update(account);

            return View("Edit", model);
        }

        public ActionResult New()
        {
            Account model = new Account();
            return View("Edit", model);
        }

        [HttpPost]
        public ActionResult New(Account model)
        {
            if (String.IsNullOrEmpty(model.Email))
            {
                TempData["error"] = "Please enter an email address, and try again.";
                return View("Edit", model);
            }
            if (String.IsNullOrEmpty(model.Username))
            {
                TempData["error"] = "Please enter a username, and try again.";
                return View("Edit", model);
            }
            if (String.IsNullOrEmpty(model.Password))
            {
                TempData["error"] = "Please enter a password, and try again.";
                return View("Edit", model);
            }

            var test = unitOfWork.AccountRepository.Get(a => a.Email == model.Email || a.Username == model.Username);
            if (test.Count() > 0)
            {
                TempData["error"] = "A user already exists with this email or username.  Please try again.";
                return View("Edit", model);
            }

            Account account = unitOfWork.AccountRepository.CreateNewUser(model);

            if (account == null)
            {
                TempData["error"] = "There was an error saving the account.  Please try again.";
                return View("Edit", model);
            }

            TempData["msg"] = "New user was added successfully!";
            return RedirectToAction("Edit", new { id = account.Id });
        }

        [RoleAuthorize(Roles = AuthRoles.Admin)]
        public ActionResult Delete([DefaultValue("")]string id)
        {
            if (unitOfWork.AccountRepository.AccountCount() == 1)
            {
                TempData["error"] = "You cannot delete the last user.";
                return RedirectToAction("Index");
            }
            Account model = unitOfWork.AccountRepository.GetByID(id);
            if (model.Id == unitOfWork.Session.CurrentUser.Id)
            {
                TempData["error"] = "You cannot delete the same account you are logged in under.";
                return RedirectToAction("Index");
            }

            if (model != null)
            {
                unitOfWork.AccountRepository.Delete(model);
                unitOfWork.Save();
                TempData["msg"] = "User deleted successfully!";
            }
            else
            {
                TempData["error"] = "Could not find the specified user.";
            }
            return RedirectToAction("Index");
        }
    }
}

src/SourPickleCMS.Core.Admin/Views/Shared/PartialViews/_ConfirmDeleteCategory.cshtml
<h2>Confirm Delete</h2>
<p>
    Are you sure you want to delete this category?<br /><br />
    It will be gone forever.
</p><br />
@Html.ActionLink("Delete", "DeleteCategory", "Posts", new { id = ViewBag.CategoryID, ContentType = ViewBag.ContentType }, new { @class = "btn" })
<a href="javascript://" onclick="$.modal.close();" >Cancel</a>

src/SourPickleCMS.Core.Admin/Views/Shared/PartialViews/_ConfirmDeleteMenu.cshtml
<h2>Confirm Delete</h2>
<p>
    Are you sure you want to delete this menu?<br /><br />
    It will be gone forever.
</p><br />
@Html.ActionLink("Delete", "DeleteMenu", "Home", new { slug = ViewBag.CategorySlug }, new { @class = "btn" })
<a href="javascript://" onclick="$.modal.close();" >Cancel</a>

src/SourPickleCMS.Core.Admin/Views/Shared/PartialViews/_ConfirmDeleteSingle.cshtml
<h2>Confirm Delete</h2>
<p>
    Are you sure you want to delete this item?<br /><br />
    It will be gone forever.
</p><br />
@Html.ActionLink("Delete", "DeletePost", "Posts", new { id = ViewBag.PostID, ContentType = ViewBag.ContentTypeID }, new { @class = "btn" })
<a href="javascript://" onclick="$.modal.close();" >Cancel</a>

src/SourPickleCMS.Core.Admin/Views/Shared/PartialViews/_ConfirmDeleteUser.cshtml
<h2>Confirm Delete</h2>
<p>
    Are you sure you want to delete this user?<br /><br />
</p><br />
@Html.ActionLink("Delete", "Delete", "Users", new { id = ViewBag.AccountID }, new { @class = "btn" })
<a href="javascript://" onclick="$.modal.close();" >Cancel</a>

src/SourPickleCMS.Core.Admin/Views/Shared/PartialViews/_NewAjaxCategory.cshtml
@model Category
@using SourPickleCMS.Core.Models

<h2>Add New Category</h2>

<div class="field input">
	<label>Name:</label>
	<div class="fields">
        @Html.TextBoxFor(m => m.Name)
	</div> <!-- .fields -->
</div> <!-- .field --><br />

<div class="field input">
	<label>Slug:</label>
	<div class="fields">
        @Html.TextBoxFor(m => m.Slug)
	</div> <!-- .fields -->
</div> <!-- .field --><br />

<div class="field input">
	<label>Default Template:</label>
	<div class="fields">
        @Html.TemplateDropDownListFor(m => m.DefaultTemplate)
	</div> <!-- .fields -->
</div> <!-- .field --><br />

@Html.AntiForgeryToken()
<input type="hidden" id="ContentTypeID" name="ContentTypeID" value="@ViewBag.ContentTypeID" />
<div class="actions">
	<button type="submit" class="btn" onclick="add_new_category()">Add Category</button> <a href="javascript://" onclick="$.modal.close();">Cancel</a>
</div> <!-- .actions -->

src/SourPickleCMS.Core.Admin/Views/Shared/PartialViews/_NewCategory.cshtml
@model Category
@using SourPickleCMS.Core.Models

@using (Html.BeginForm("NewCategory", "Posts")) {
	<div class="field input">
		<label>Name:</label>
		<div class="fields">
            @Html.TextBoxFor(m => m.Name)
		</div> <!-- .fields -->
	</div> <!-- .field --><br />

	<div class="field input">
		<label>Slug:</label>
		<div class="fields">
            @Html.TextBoxFor(m => m.Slug)
		</div> <!-- .fields -->
	</div> <!-- .field --><br />

    <div class="field input">
		<label>Default Template:</label>
		<div class="fields">
            @Html.TemplateDropDownListFor(m => m.DefaultTemplate)
		</div> <!-- .fields -->
	</div> <!-- .field --><br />

    @Html.AntiForgeryToken()
    <input type="hidden" id="ContentType" name="ContentType" value="@ViewBag.ContentType.Slug" />
	<div class="actions">
		<button type="submit" class="btn">Add Category</button>
	</div> <!-- .actions -->
}

src/SourPickleCMS.Core.Admin/Views/Shared/PartialViews/_NewCustomFieldForm.cshtml
@model Field
@using SourPickleCMS.Core.Models

<p><strong>New Custom Field:</strong></p>
	
<div class="field input">
	<div class="fields">
        @Html.CustomFieldsDropDownList("Name", new { style = "width: 155px", id = "custom_field_name_select", name = "custom_field_name_select" }, (String)ViewBag.ContentType.Slug)
	</div> <!-- .fields -->
    <label>or, Enter a new name:</label>
	<div class="fields">
        @Html.TextBoxFor(m => m.Name, new { id = "custom_field_name", name = "custom_field_name" })
	</div> <!-- .fields -->
</div> <!-- .field --><br />

<div class="field input">
	<label>Value:</label>
	<div class="fields">
        @Html.TextBoxFor(m => m.Value, new { id = "custom_field_value", name = "custom_field_value" })
	</div> <!-- .fields -->
</div> <!-- .field --><br />

<div class="actions">
	<button type="button" class="btn" onclick="add_custom_field();">Add Custom Field</button>
    <img id="custom_field_loader" src="/Areas/Admin/Content/Css/img/loader.gif" alt="loader" style="height: 24px; display: none; vertical-align: bottom;" /><br />
    <div style="color: #f00; margin-top: 5px;" id="custom_field_status_message"></div>
</div> <!-- .actions -->