src/SourPickleCMS.Core.Admin/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using SourPickleCMS.Core.Attributes;
using SourPickleCMS.Core.Controllers;
using SourPickleCMS.Core.Helpers;
using SourPickleCMS.Core.Models;
using SourPickleCMS.Core.Models.ViewModels;

namespace SourPickleCMS.Core.Admin.Controllers
{
    [RoleAuthorize(Roles = AuthRoles.Writer)]
    public class MainController : SourPickleController
    {
        public ActionResult Index()
        {
            AdminDashboardViewModel model = new AdminDashboardViewModel();

            model.ThemeName = unitOfWork.Session.Settings["Theme"];
            model.SiteVersion = ConfigurationManager.AppSettings["SourPickleVersion"];

            model.PageCount = unitOfWork.PostRepository.GetPostCountByType("page");
            model.PostCount = unitOfWork.PostRepository.GetPostCountByType("blog");
            model.UserCount = unitOfWork.AccountRepository.AccountCount();
            model.CommentCount = unitOfWork.PostRepository.TotalCommentsCount();
            //model.PendingCommentCount = unitOfWork.CommentRepository.Get(c => c.IsApproved == false && c.IsDeleted == false).Count();
            //model.RecentComments = unitOfWork.CommentRepository.Get(orderBy: rc => rc.OrderByDescending(o => o.CreateDate)).Take(5);

            return View(model);
        }

        public ActionResult Editor()
        {
            return View();
        }

        #region Blocks

        public ActionResult Blocks()
        {
            BlocksViewModel model = new BlocksViewModel();
            model.ThemeBlocks = unitOfWork.BlockRepository.GetBlocksByTheme(unitOfWork.Session.Settings["Theme"]);

            model.AdminBlocks = ThemeHelpers.GetBlocks(Server.MapPath("~/Areas/Admin/Blocks"));
            model.UserBlocks = ThemeHelpers.GetBlocks(Server.MapPath("~/Blocks"));
            model.Regions = ThemeHelpers.GetRegions(Server.MapPath("~/Themes/" + unitOfWork.Session.Settings["Theme"]));

            return View(model);
        }

        [HttpPost]
        [ValidateInput(false)]
        [BypassAntiForgeryTokenAttribute]
        public ActionResult SaveBlock(Block model)
        {
            model.Theme = unitOfWork.Session.Settings["Theme"];
            if (model.Id == null)
            {
                unitOfWork.BlockRepository.Save(model);
                TempData["msg"] = "Block added successfully.";
            }
            else
            {
                unitOfWork.BlockRepository.Update(model);
                TempData["msg"] = "Block updated successfully.";
            }
            return RedirectToAction("Blocks");
        }

        #endregion

        #region ContentTypes

        public ActionResult ContentTypes()
        {
            IList<ContentType> model = unitOfWork.ContentTypeRepository.GetCustomContentTypes();

            return View(model);
        }

        public ActionResult NewContentType()
        {
            return View("EditContentType", new ContentType());
        }

        [RoleAuthorize(Roles = AuthRoles.Admin)]
        public ActionResult EditContentType([DefaultValue("")]string slug)
        {
            ContentType model = unitOfWork.ContentTypeRepository.GetBySlug(slug);
            return View(model);
        }

        [HttpPost]
        [RoleAuthorize(Roles = AuthRoles.Admin)]
        public ActionResult EditContentType(ContentType model)
        {
            if (String.IsNullOrWhiteSpace(model.Name))
            {
                TempData["error"] = "No Content Type name provided.  Please try again.";
                return View(model);
            }
            if (String.IsNullOrWhiteSpace(model.PluralName))
            {
                TempData["error"] = "No Content Type plural name provided.  Please try again.";
                return View(model);
            }
            if (String.IsNullOrWhiteSpace(model.Slug))
            {
                TempData["error"] = "No Content Type slug provided.  Please try again.";
                return View(model);
            }
            model.IsCustom = true;
            IList<Field> fields = new List<Field>();

            if (model.Fields != null)
            {
                foreach (Field f in model.Fields.OrderBy(o => o.Order))
                {
                    if (String.IsNullOrWhiteSpace(f.Name)) continue;
                    f.IsCustomField = true;
                    fields.Add(f);
                }
            }
            else
            {
                model.Fields = new List<Field>();
            }

            if (model.Id == null)
            {
                unitOfWork.ContentTypeRepository.Save(model);
                TempData["msg"] = "Content Type saved successfully!";
            }
            else
            {
                unitOfWork.ContentTypeRepository.Update(model);
                TempData["msg"] = "Content Type updated successfully!";
            }
            return RedirectToAction("EditContentType", new { slug = model.Slug });
        }

        #endregion

        #region Themes

        [RoleAuthorize(Roles = AuthRoles.Admin)]
        public ActionResult Themes()
        {
            string currentTheme = unitOfWork.Session.Settings["Theme"];
            IList<ThemeViewModel> themes = new List<ThemeViewModel>();
            var themesFolder = new DirectoryInfo(Server.MapPath("~/Themes"));
            string[] names = themesFolder.GetDirectories("*", SearchOption.TopDirectoryOnly).Select(x => x.Name).OrderBy(x => x).ToArray();

            foreach (string name in names)
            {
                ThemeViewModel theme = new ThemeViewModel();
                StreamReader sr = null;
                try
                {
                    sr = new StreamReader(themesFolder + "/" + name + "/ThemeInfo.txt");
                }
                catch
                {
                    continue;
                }
                theme.Folder = name;
                theme.Info = new Dictionary<string, string>();
                if (currentTheme == name) theme.IsCurrent = true;

                do
                {
                    string line = sr.ReadLine();
                    if (String.IsNullOrWhiteSpace(line) == true || line.Substring(0, 1) == "*") continue;
                    string key = line.Substring(0, line.IndexOf(':'));
                    string value = line.Substring(line.IndexOf(':') + 1);

                    theme.Info.Add(key, value);
                } while (!sr.EndOfStream);

                themes.Add(theme);
                sr.Close();
            }
            return View(themes);
        }

        [RoleAuthorize(Roles = AuthRoles.Admin)]
        public ActionResult SetTheme(string name)
        {
            if (!String.IsNullOrWhiteSpace(name)) {
                var themesFolder = new DirectoryInfo(Server.MapPath("~/Themes/" + name));
                try
                {
                    string[] names = themesFolder.GetFiles("*", SearchOption.TopDirectoryOnly).Select(x => x.Name).OrderBy(x => x).ToArray();

                    unitOfWork.SettingRepository.UpdateSetting("Theme", name);
                    unitOfWork.SettingRepository.AddThemeSettings(name, themesFolder.FullName);
                    unitOfWork.Session.Settings = unitOfWork.SettingRepository.GetSettingsDictionary();

                    TempData["msg"] = "New theme set successfully.";
                }
                catch (Exception err)
                {
                    if (err is DirectoryNotFoundException)
                    {
                        TempData["error"] = "The specified theme does not exist.";
                    }
                    else
                    {
                        TempData["error"] = "There was an error setting the new theme.";
                    }
                }
            }

            return RedirectToAction("Themes");
        }

        #endregion

        #region Settings

        [RoleAuthorize(Roles = AuthRoles.Admin)]
        public ActionResult GeneralSettings()
        {
            return View(unitOfWork.Session.Settings);
        }

        [HttpPost]
        [RoleAuthorize(Roles = AuthRoles.Admin)]
        public ActionResult GeneralSettings(FormCollection values)
        {
            foreach (string key in values.Keys)
            {
                if (key.Substring(0, 1) == "_") continue;
                string[] rval = (string[])values.GetValue(key).RawValue;
                unitOfWork.SettingRepository.UpdateSetting(key, rval[0], false);
                unitOfWork.Session.Settings[key] = rval[0];
            }
            unitOfWork.Save();
            TempData["msg"] = "Settings updated successfully.";

            return RedirectToAction("GeneralSettings");
        }

        [RoleAuthorize(Roles = AuthRoles.Admin)]
        public ActionResult UserSettings()
        {
            return View(unitOfWork.Session.Settings);
        }

        [HttpPost]
        [RoleAuthorize(Roles = AuthRoles.Admin)]
        public ActionResult UserSettings(FormCollection values)
        {
            foreach (string key in values.Keys)
            {
                if (key.Substring(0, 1) == "_") continue;
                string[] rval = (string[])values.GetValue(key).RawValue;
                unitOfWork.SettingRepository.UpdateSetting(key, rval[0], false);
                unitOfWork.Session.Settings[key] = rval[0];
            }
            unitOfWork.Save();
            TempData["msg"] = "Settings updated successfully.";

            return RedirectToAction("UserSettings");
        }

        [RoleAuthorize(Roles = AuthRoles.Admin)]
        public ActionResult DisplaySettings()
        {
            return View(unitOfWork.Session.Settings);
        }

        [HttpPost]
        [RoleAuthorize(Roles = AuthRoles.Admin)]

src/SourPickleCMS.Core.Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SourPickleCMS.Core.Services.DataAccess;
using SourPickleCMS.Core.Models;
using SourPickleCMS.Core.Attributes;
using System.ComponentModel;
using SourPickleCMS.Core.Controllers;

namespace SourPickleCMS.Core.Admin.Controllers
{
    [RoleAuthorize(Roles = AuthRoles.Admin)]
    public class UsersController : SourPickleController
    {
        public ActionResult Index()
        {
            IEnumerable<Account> model = unitOfWork.AccountRepository.Get();

            return View(model);
        }

        public ActionResult Edit([DefaultValue("")]string id)
        {
            Account model = new Account();

            try
            {
                model = unitOfWork.AccountRepository.GetByID(id);
            }
            catch
            {
                model = null;
            }
            if (model == null) return RedirectToAction("Index");
            model.Password = "";

            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Account model)
        {
            Account account = unitOfWork.AccountRepository.GetByID(model.Id);

            account.Email = model.Email;
            account.Name = model.Name;
            account.Username = model.Username;
            account.LockedReason = model.LockedReason;
            account.IsLocked = model.IsLocked;
            account.IsSuspended = model.IsSuspended;
            account.Role = model.Role;
            account.EmailVerified = model.EmailVerified;

            if (!String.IsNullOrEmpty(model.Password))
            {
                model.Password = SecurityHelper.GetHashedString(model.Password + "$" + account.PasswordSalt);
            }

            unitOfWork.AccountRepository.Update(account);

            return View("Edit", model);
        }

        public ActionResult New()
        {
            Account model = new Account();
            return View("Edit", model);
        }

        [HttpPost]
        public ActionResult New(Account model)
        {
            if (String.IsNullOrEmpty(model.Email))
            {
                TempData["error"] = "Please enter an email address, and try again.";
                return View("Edit", model);
            }
            if (String.IsNullOrEmpty(model.Username))
            {
                TempData["error"] = "Please enter a username, and try again.";
                return View("Edit", model);
            }
            if (String.IsNullOrEmpty(model.Password))
            {
                TempData["error"] = "Please enter a password, and try again.";
                return View("Edit", model);
            }

            var test = unitOfWork.AccountRepository.Get(a => a.Email == model.Email || a.Username == model.Username);
            if (test.Count() > 0)
            {
                TempData["error"] = "A user already exists with this email or username.  Please try again.";
                return View("Edit", model);
            }

            Account account = unitOfWork.AccountRepository.CreateNewUser(model);

            if (account == null)
            {
                TempData["error"] = "There was an error saving the account.  Please try again.";
                return View("Edit", model);
            }

            TempData["msg"] = "New user was added successfully!";
            return RedirectToAction("Edit", new { id = account.Id });
        }

        [RoleAuthorize(Roles = AuthRoles.Admin)]
        public ActionResult Delete([DefaultValue("")]string id)
        {
            if (unitOfWork.AccountRepository.AccountCount() == 1)
            {
                TempData["error"] = "You cannot delete the last user.";
                return RedirectToAction("Index");
            }
            Account model = unitOfWork.AccountRepository.GetByID(id);
            if (model.Id == unitOfWork.Session.CurrentUser.Id)
            {
                TempData["error"] = "You cannot delete the same account you are logged in under.";
                return RedirectToAction("Index");
            }

            if (model != null)
            {
                unitOfWork.AccountRepository.Delete(model);
                unitOfWork.Save();
                TempData["msg"] = "User deleted successfully!";
            }
            else
            {
                TempData["error"] = "Could not find the specified user.";
            }
            return RedirectToAction("Index");
        }
    }
}

src/SourPickleCMS.Core.Admin/Views/Shared/_Email.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<body>
    @RenderBody()
</body>
</html>

src/SourPickleCMS.Core.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>@Html.AppSettings()["SiteTitle"] Admin | @ViewBag.Title</title>

    <!-- Mobile viewport optimized: j.mp/bplateviewport -->
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

    <!-- CSS: implied media=all -->
    <link rel="stylesheet" href="/Areas/Admin/Content/Css/All.css" />
    <!-- end CSS-->

    <!-- Javascript (Put all other scripts at bottom of page for faster loading.) -->
    <script src="/Scripts/Libs/jquery-1.7.1.min.js" type="text/javascript"></script>
    <!-- end Javascript -->

    @RenderSection("head", false)
</head>
<body>

    <header id="head">
        <div class="left">
            <a href="http://www.sourpickle-cms.com" class="logo">Sour Pickle CMS</a>&nbsp; |&nbsp;
            <a href="/Admin/">Dashboard</a>
        </div>
        <div class="right">
            Hi, 
            @Html.ActionLink((string)ViewBag.Account.Username, "Profile", "User", new { id = ViewBag.Account.Username, Area = "" }, null) |
            @Html.ActionLink("Logout", "LogOff", "User", new { Area = "" }, null) |
            <a href="/">Visit Website</a>
        </div>
    </header> <!-- Header -->

    <div id="sidebar">
        <ul>
            <li name="site"><a href="javascript://"><img src="/Areas/Admin/Content/Images/icons/menu/layout.png" alt="" /> Site</a>
                <ul>
                    <li name="dashboard"><a href="/Admin/">Dashboard</a></li>
                    <li name="themes">@Html.ActionLink("Themes", "Themes", "Main")</li>
                    <li name="menus">@Html.ActionLink("Menus", "Menus", "Main", new { id = "" }, null)</li>
                    <li name="content_types">@Html.ActionLink("Content Types", "ContentTypes", "Main")</li>
                    <li name="blocks">@Html.ActionLink("Blocks", "Blocks", "Main")</li>
                    <li name="editor">@Html.ActionLink("Code Editor", "Editor", "Main")</li>
                </ul>
            </li>
            <li name="site"><a href="javascript://"><img src="/Areas/Admin/Content/Images/icons/menu/settings.png" alt="" /> Settings</a>
                <ul>
                    <li name="gen_settings">@Html.ActionLink("General Settings", "GeneralSettings", "Main")</li>
                    <li name="user_settings">@Html.ActionLink("User Settings", "UserSettings", "Main")</li>
                    <li name="display_settings">@Html.ActionLink("Display Settings", "DisplaySettings", "Main")</li>
                    <li name="email_settings">@Html.ActionLink("Email Settings", "EmailSettings", "Main")</li>
                    <li name="theme_settings">@Html.ActionLink("Theme Settings", "ThemeSettings", "Main")</li>
                </ul>
            </li>
            <li name="pages"><a href="javascript://"><img src="/Areas/Admin/Content/Images/icons/menu/pages.png" alt="" /> Pages</a>
                <ul>
                    <li name="all_page">@Html.ActionLink("All Pages", "Index", "Posts", new { ContentType = "page" }, null)</li>
                    <li name="new_page">@Html.ActionLink("Add New Page", "New", "Posts", new { ContentType = "page" }, null)</li>
                </ul>
            </li>
            <li name="blogs"><a href="javascript://"><img src="/Areas/Admin/Content/Images/icons/menu/pen.png" alt="" /> Blog Posts</a>
                <ul>
                    <li name="all_blog">@Html.ActionLink("All Blog Posts", "Index", "Posts", new { ContentType = "blog" }, null)</li>
                    <li name="new_blog">@Html.ActionLink("Add New Blog Post", "New", "Posts", new { ContentType = "blog" }, null)</li>
                    <li name="blog_categories">@Html.ActionLink("Categories", "Categories", "Posts", new { ContentType = "blog" }, null)</li>
                </ul>
            </li>
            <li name="media"><a href="javascript://"><img src="/Areas/Admin/Content/Images/icons/menu/movie.png" alt="" /> Media</a>
                <ul>
                    <li name="all_media">@Html.ActionLink("All Media", "Media", "Posts", null, null)</li>
                    <li name="new_media">@Html.ActionLink("Add Media", "NewMedia", "Posts", null, null)</li>
                    <li name="media_categories">@Html.ActionLink("Categories", "Categories", "Posts", new { ContentType = "media" }, null)</li>
                </ul>
            </li>
            <li name="users"><a href="javascript://"><img src="/Areas/Admin/Content/Images/icons/menu/users.png" alt="" /> Users</a>
                <ul>
                    <li name="all_users">@Html.ActionLink("All Users", "Index", "Users")</li>
                    <li name="new_user">@Html.ActionLink("Add New User", "New", "Users")</li>
                </ul>
            </li>
            @Html.RenderContentTypeMenus()
            @Html.RenderCustomMenus()
        </ul>
        <a href="#collapse" id="menucollapse">&#9664; Collapse sidebar</a>
        <input type="hidden" id="current_menu" value="@ViewBag.Page" />
    </div> <!-- Sidebar -->

    <div id="content" class="white">
        @if (TempData["msg"] != null)
        {
            <div id="msg_box" class="notif tip bloc">
                <strong>Success: </strong>
                @TempData["msg"]
                <a href="#" class="close">x</a>
            </div>
        }
        @if (TempData["error"] != null)
        {
            <div id="msg_box" class="notif error bloc">
                <strong>Error: </strong>
                @TempData["error"]
                <a href="#" class="close">x</a>
            </div>
        }

        <h1>@RenderSection("header", false)</h1>
        @RenderBody()
    </div>

    <div id="modal_dialog">
        <div id="dialog_content">
            
        </div>
        <div id="loading_overlay">
            <div id="loading_notif"><img src="/Areas/Admin/Content/Css/img/loader.gif" /></div>
        </div>
    </div>
    <script src="/Areas/Admin/Scripts/All.js" type="text/javascript"></script>
    <script src="/Areas/Admin/Scripts/Main.js" type="text/javascript"></script>
    @RenderSection("scripts", false)
@*    @Raven.Client.MvcIntegration.RavenProfiler.CurrentRequestSessions();
*@    <script type="text/javascript">
        $(function () {
            ReadyMade.init();
        });
    </script>
</body>
</html>